### ISSUE TITLE
ValueError: sample larger than population

### ISSUE THREAD

**Issue by bradymwilliams** [m000/cliutils#1]
Probably due to my own lack of understanding I am getting this error
Traceback (most recent call last):
  File "/Users/username/Downloads/utorrent_tidy.py", line 64, in <module>
    savepath = os.path.commonprefix(random.sample(allpaths, SAVEPATH_SAMPLE_SIZE))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/random.py", line 320, in sample
    raise ValueError("sample larger than population")
ValueError: sample larger than population

Perhaps I am running it wrong? Any help is appreciated

Found the solution thanks to #python on freenode.
changed line 64 to savepath = os.path.commonprefix(random.sample(allpaths, len(allpaths)))

**Comment by m000** [comment]
You are right. This wouldn't work if you have <10 torrents. I changed the used sample size to min(SAVEPATH_SAMPLE_SIZE, len(allpaths)) which should not throw the error (commit d19d766445f1f5595d39f2eb2ba0b9c489aaf61c).

Still, I'd guess that in the next run you will be asked to reduce your SAVEPATH_SAMPLE_SIZE. Right?

In general, if you have too few torrents or you save data in different filesystems the sampling approach will not work well. In this case, the best solution would be to add a command line option `-p <path>`. Only torrents saved somewhere under `<path>` will be processed.

**Comment by m000** [comment]
I'll leave this open until I find some time to implement the proposed command line option. Patches are always welcome.

**Comment by bradymwilliams** [comment]
Yeah I was asked to reduce on second run. But overall the script worked and
saved me a whole lot of time and a headache and for that I thank you!
